services:
  - type: web
    name: vnquant-stock-analyzer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: PORT
        value: 8501
    autoDeploy: true
